### ISSUE TITLE
bug: floor division breaks the parser

### ISSUE THREAD

**Issue by lopi-py** [tree-sitter-grammars/tree-sitter-luau#7]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-luau

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263)

### Describe the bug

Whenever I use floor division, the parser reports an error.
![image](https://github.com/tree-sitter-grammars/tree-sitter-luau/assets/70210066/400cbe73-37d8-48e6-acb6-fc9c8e8beaa4)

### Steps To Reproduce/Bad Parse Tree

- Create a file `source.luau`
- Run `tree-sitter parse source.luau`

### Expected Behavior/Parse Tree

There should be no errors.

### Repro

```Lua
local foo = 10
foo //= 2.5
```

**Comment by amaanq** [comment]
thanks for the report, fixed
